const creatureNames = [
  "Acolyte",
  "Ape",
  "Awakened Shrub",
  "Axe Beak",
  "Baboon",
  "Badger",
  "Bandit",
  "Bat",
  "Black Bear",
  "Blink Dog",
  "Blood Hawk",
  "Boar",
  "Camel",
  "Cat",
  "Cockatrice",
  "Commoner",
  "Constrictor Snake",
  "Crab",
  "Crocodile",
  "Cultist",
  "Darkmantle",
  "Deep Gnome (Svirfneblin)",
  "Deer",
  "Draft Horse",
  "Dretch",
  "Drow",
  "Dust Mephit",
  "Eagle",
  "Elk",
  "Flying Snake",
  "Flying Sword",
  "Frog",
  "Giant Badger",
  "Giant Bat",
  "Giant Centipede",
  "Giant Crab",
  "Giant Fire Beetle",
  "Giant Frog",
  "Giant Goat",
  "Giant Lizard",
  "Giant Owl",
  "Giant Poisonous Snake",
  "Giant Rat",
  "Giant Rat (Diseased)",
  "Giant Sea Horse",
  "Giant Wasp",
  "Giant Weasel",
  "Giant Wolf Spider",
  "Gnoll",
  "Goat",
  "Goblin",
  "Gray Ooze",
  "Grimlock",
  "Guard",
  "Hawk",
  "Hobgoblin",
  "Homunculus",
  "Hyena",
  "Ice Mephit",
  "Jackal",
  "Kobold",
  "Lemure",
  "Lizard",
  "Lizardfolk",
  "Magma Mephit",
  "Magmin",
  "Mastiff",
  "Merfolk",
  "Mule",
  "Noble",
  "Octopus",
  "Orc",
  "Owl",
  "Panther",
  "Poisonous Snake",
  "Pony",
  "Pseudodragon",
  "Quipper",
  "Rat",
  "Raven",
  "Reef Shark",
  "Riding Horse",
  "Rust Monster",
  "Sahuagin",
  "Satyr",
  "Scorpion",
  "Scout",
  "Sea Horse",
  "Shadow",
  "Shrieker",
  "Skeleton",
  "Spider",
  "Sprite",
  "Steam Mephit",
  "Stirge",
  "Swarm of Bats",
  "Swarm of Beetles",
  "Swarm of Centipedes",
  "Swarm of Insects",
  "Swarm of Rats",
  "Swarm of Ravens",
  "Swarm of Spiders",
  "Swarm of Wasps",
  "Thug",
  "Tribal Warrior",
  "Violet Fungus",
  "Vulture",
  "Warhorse",
  "Warhorse Skeleton",
  "Weasel",
  "Wolf",
  "Worg",
  "Zombie"
]

export default creatureNames;